# Generated by Django 4.1.7 on 2023-06-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=20)),
                ('marque', models.CharField(max_length=20)),
                ('achat', models.DateField(blank=True, null=True)),
                ('place', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('longueur', models.FloatField()),
                ('climatisation', models.BooleanField()),
            ],
        ),
    ]
