# Generated by Django 4.1.7 on 2023-06-01 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('producteur', models.CharField(max_length=100)),
                ('acteur', models.TextField()),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('duree', models.TimeField()),
                ('syno', models.TextField(blank=True, null=True)),
                ('genre', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projet.genre')),
            ],
        ),
    ]
